;; ACCEPTANCE TESTS
(ns marketing.acceptance
  (:use [clj-webdriver.taxi :only [set-driver! to click exists? find-element
                                   input-text submit quit drag-and-drop-by] :as scraper]
        [clojure.core]
        [cms.handler]
        [expectations]
        [pallet.action :only[with-action-options]]
        [pallet.configure :only[compute-service]]
        [pallet.api :only[converge]]))

;; ONLINE ADVERTISING MANAGEMENT
(deftest user-can-fund-account false)
(deftest user-can-add-credit-card false)
(deftest user-can-remove-create-card false)
(deftest user-can-create-budget-for-market-matrix false)
(deftest user-can-remove-budget-for-market-martrix false)
(deftest user-can-edit-budget-for-market-martrix false)
(deftest user-can-create-budget-for-market-vector false)
(deftest user-can-remove-budget-for-market-vector false)
(deftest user-can-edit-budget-for-market-vector false)
(deftest user-can-create-budget-for-landing-site false)
(deftest user-can-remove-budget-for-landing-site false)
(deftest user-can-edit-budget-for-landing-site false)
(deftest user-can-create-budget-for-campaign false)
(deftest user-can-remove-budget-for-campaign false)
(deftest user-can-edit-budget-for-campaign false)
(deftest user-can-create-budget-for-adgroup false)
(deftest user-can-remove-budget-for-adgroup false)
(deftest user-can-edit-budget-for-adgroup false)
(deftest user-can-create-budget-for-ad false)
(deftest user-can-remove-budget-for-ad false)
(deftest user-can-edit-budget-for-ad false)
(deftest user-can-edit-budget-for-offer false)
(deftest user-can-create-campaign false)
(deftest user-can-edit-campaign false)
(deftest user-can-add-ad-networks-to-campaign false)
(deftest user-can-remove-ad-networks-to-campaign false)
(deftest user-can-disable-ad-networks-to-campaign false)
(deftest user-can-enable-ad-networks-to-campaign false)
(deftest user-can-clone-campaign false)
(deftest user-can-create-ad-group false)
(deftest user-can-edit-ad-group false)
(deftest user-can-remove-ad-group false)
(deftest user-can-enable-ad-group false)
(deftest user-can-disable-ad-group false)
(deftest user-can-create-display-ad false)
(deftest user-can-remove-display-ad false)
(deftest user-can-edit-display-ad false)
(deftest user-can-enable-display-ad false)
(deftest user-can-disable-display-ad false)
(deftest user-can-create-text-ad false)
(deftest user-can-remove-text-ad false)
(deftest user-can-edit-text-ad false)
(deftest user-can-enable-text-ad false)
(deftest user-can-disable-text-ad false)
(deftest user-can-have-ad-participate-in-ab-testing false)
(deftest user-can-associate-keywords-with-ad false)
(deftest user-can-create-keyword-set false)
(deftest user-can-remove-keyword-set false)
(deftest user-can-add-word-to-keyword-set false)
(deftest user-can-remove-word-from-keyword-set false)
(deftest user-can-edit-keyword-bid false)
